# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23bc9156266d526758243c1337880f4e6f666ef486d847d165ce43455033bd24449f1dc0cbb7e0660e39e8c7d2a2ab52ccc255175d2d3fa446846c5da71b2ff2

test:
  secret_key_base: eaa69f2938b760f08744b3156d665367ce00e92eebab5ecbb205f47282a83c258b4ed70ff8505a23392b92bb5d373b66d77ac93e1ef0370371904247339f765b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
